<a href="https://colab.research.google.com/github/fakiis/Dsp2020/blob/master/DSP_%E6%9C%9F%E6%9C%AB%E8%80%83.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget "https://raw.githubusercontent.com/AllenDowney/ThinkDSP/master/code/thinkdsp.py"
import thinkdsp as td
import scipy as sp
import numpy as np

--2020-06-30 15:04:56--  https://raw.githubusercontent.com/AllenDowney/ThinkDSP/master/code/thinkdsp.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48703 (48K) [text/plain]
Saving to: ‘thinkdsp.py’

thinkdsp.py         100%[===================>]  47.56K  --.-KB/s    in 0.02s   

2020-06-30 15:04:57 (1.90 MB/s) - ‘thinkdsp.py’ saved [48703/48703]



[1]\
(a)

In [ ]:
x1=[1,0,0,0,0,0,0,0]
X1=np.fft.fft(x1)
X1

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

(b)

In [ ]:
x2=[1,1,1,1,1,1,1,1]
np.fft.fft(x2)

array([8.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

(c)

In [ ]:
x3=[1,-1,1,-1,1,-1,1,-1]
np.fft.fft(x3)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 8.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

(d)

In [ ]:
x4=[3,0,2,0,2,0,2,0]
np.fft.fft(x4)

array([9.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 9.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

(e)當x[n]為實數時，X[k]與X[N-k]為共軛複數

(f)

In [ ]:
X5=[1,1,0,0,0,0,1,1]
X6=[1,1,0,0,0,0,0,1]
np.fft.ifft(X5),np.fft.ifft(X6)

(array([ 0.5      +0.j   ,  0.3017767-0.125j,  0.       +0.j   ,
        -0.0517767+0.125j,  0.       +0.j   , -0.0517767-0.125j,
         0.       +0.j   ,  0.3017767+0.125j]),
 array([ 0.375    +0.j,  0.3017767+0.j,  0.125    +0.j, -0.0517767+0.j,
        -0.125    +0.j, -0.0517767+0.j,  0.125    +0.j,  0.3017767+0.j]))

(g)

In [ ]:
x7=[1,1,0,0]
x8=[1,1,0,0,0,0,0,0]
x9=[1,1]
np.fft.fft(x7),np.fft.fft(x8),np.fft.fft(x9)

(array([2.+0.j, 1.-1.j, 0.+0.j, 1.+1.j]),
 array([2.        +0.j        , 1.70710678-0.70710678j,
        1.        -1.j        , 0.29289322-0.70710678j,
        0.        +0.j        , 0.29289322+0.70710678j,
        1.        +1.j        , 1.70710678+0.70710678j]),
 array([2.+0.j, 0.+0.j]))

[2]\
(a)\
(b)

In [5]:
xn=[1,1,1,1]
w=[1,1]
y=np.convolve(xn,w,mode='full')
y

array([1, 2, 2, 2, 1])

(c)(d)

In [ ]:
XN=np.fft.fft(xn)
W=np.fft.fft(w)
Y=np.fft.fft(y)
np.convolve(XN,W,mode='full'),Y

(array([8.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]),
 array([ 8.        +0.j        , -1.30901699-0.95105652j,
        -0.19098301-0.58778525j, -0.19098301+0.58778525j,
        -1.30901699+0.95105652j]))

[4]

In [31]:
xnn=np.array([10,11,12,13,14,15,16,17])
HN=np.array([1,1,0,0,0,0,0,0])
XNN=td.Wave(xnn,framerate=8)
kk=XNN.make_spectrum(full=True)
product = kk * HN
product.plot()

AttributeError: ignored